name = "fresh-root"
main = "worker/index.ts"
compatibility_date = "2024-12-19"

[env.production]

[env.production.vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBxZB9IhDoHk1iX4bE71_Qyu_VUST_56Ck"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "studio-3628697519-35eff.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "studio-3628697519-35eff"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "studio-3628697519-35eff.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:896789236509:web:b1e9a4558ab4793dc3aff4"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "896789236509"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-50P2PGN5QQ"
FIREBASE_PROJECT_ID = "studio-3628697519-35eff"

[[env.production.secrets]]
name = "GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64"

[env.preview]

[env.preview.vars]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBxZB9IhDoHk1iX4bE71_Qyu_VUST_56Ck"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "studio-3628697519-35eff.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "studio-3628697519-35eff"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "studio-3628697519-35eff.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:896789236509:web:b1e9a4558ab4793dc3aff4"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "896789236509"
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID = "G-50P2PGN5QQ"
FIREBASE_PROJECT_ID = "studio-3628697519-35eff"

[[env.preview.secrets]]
name = "GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64"
